name: ntutepstofithealths_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_name: ^0.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  social_share_plugin: ^0.3.1+1
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.7
  table_calendar: ^2.2.3
  firebase_helpers: ^0.1.5
  video_player: ^0.10.9
  font_awesome_flutter: ^8.4.0
  decimal: ^0.3.3
  pedometer: ^0.0.5
  percent_indicator: ^1.0.14
  provider: ^3.1.0
  image_picker: ^0.6.1+11
  path: ^1.6.4
  uuid: ^2.0.4







dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7



flutter_launcher_name:
  Name: "NtuStepToFitHealth"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
        - assets/images/logo.png
        - assets/images/try.png
        - assets/images/running.jpg
        - assets/images/tennis.jpg
        - assets/images/workout.jpg
        - assets/images/health.png
        - assets/images/walking.jpg
        - assets/images/football.jpg
        - assets/images/basketball.jpg
        - assets/images/Gym.jpg
        - assets/images/swimming.jpg
        - assets/images/daych.png
        - assets/images/EM.png
        - assets/images/EV.png
        - assets/images/F.png
        - assets/images/IN.png
        - assets/images/OC.png
        - assets/images/P.png
        - assets/images/S.png
        - assets/images/SO.png

        - assets/videos/Strength.mp4
        - assets/videos/fatburn.mp4
        - assets/videos/fixibility.mp4
        - assets/videos/muscle.mp4
        - assets/videos/warmup.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
